---
- name: "WEB | SERVICE | Install uwsgi"
  pip:
    name: uwsgi
    executable: pip3.5

- name: "WEB | SERVICE | Copy web service configuration"
  copy:
    src: /home/engine/scoring_engine/src/configs/web.service
    dest: /etc/systemd/system/scoring_engine-web.service
    remote_src: true

- name: "WEB | SERVICE | Enable web service"
  service:
    name: scoring_engine-web
    enabled: yes
    state: started

